### ISSUE TITLE
Contract expanded cells on selection?

### ISSUE THREAD

**Issue by wm-j-ray** [vicpenap/VPPDropDown#2]
Victor,

It's probably trivial to do, but I'd like to contract cells when using VPPDropDownTypeSelection when the user selects one of the expanded cells.

Can you advise me  as to where and how to do this?

Thanx you so much for the code you put up here.  (I'm learning a ton from folks like you).

**Comment by vicpenap** [comment]
It is, indeed :D. Since version 0.3.0, you can change dropdown's status at any time using the `expanded` property:

`@property (nonatomic, assign, getter = isExpanded) BOOL expanded`

So, whenever you want to contract it, add `dropDown.expanded = NO`.

Hope that helps.

**Comment by wm-j-ray** [comment]
Perfect.  Thanx again.

**Comment by vicpenap** [comment]
You're welcome :)
